%YAML 1.2
---
# Main configuration document

llsfrb:
  plugins: "drilling_machine,conveyor_belt,quality_control_camera,force_fitting_machine"

  log:
    level: info
    general: refbox.log
    clips: clips.log
    game: game.log

  conveyor-belt:
    enable: false
    host: !ipv4 eth0
    command_port: !tcp-port 55502
    status_port: !tcp-port 55501

  quality-control-camera:
    enable: false
    host: !ipv4 192.168.1.102
    service_port: !tcp-port 55522
    status_port: !tcp-port 55521

  drilling-machine:
    enable: false
    host: !ipv4 eth0
    command_port: !tcp-port 55512
    status_port: !tcp-port 55511
    
  force-fitting-machine:
    enable: false
    host: !ipv4 eth0
    command_port: !tcp-port 55532
    status_port: !tcp-port 55531

  clips:
    dir: "@BASEDIR@/rockin/clips"
    # Timer interval, in milliseconds
    timer-interval: 40

    main: refbox
    debug: true
    # debug levels: 0 ~ none, 1 ~ minimal, 2 ~ more, 3 ~ maximum
    debug-level: 2
    unwatch-facts: [time, signal, benchmark-state]
    unwatch-rules: [retract-time, benchmark-update-last-time,
                    net-send-beacon, net-send-BenchmarkState, net-send-OrderInfo,
                    net-send-Inventory, net-send-VersionInfo,
                    net-send-DrillingMachineStatus, net-send-ConveyorBeltStatus]

  comm:
    protobuf-dirs: ["@BASEDIR@/rockin/msgs"]

    server-port: !tcp-port 4444

    public-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4444
      send-port: !udp-port 4444
      recv-port: !udp-port 4445

    b-it-bots-peer:
      host: !ipv4 192.168.1.255
      port: !udp-port 4446
      #send-port: !udp-port 4446
      #recv-port: !udp-port 4447

    IASLab-peer:
      host: !ipv4 192.168.1.255
      port: !udp-port 4448
      #send-port: !udp-port 4448
      #recv-port: !udp-port 4449

    SPQR-peer:
      host: !ipv4 192.168.1.255
      #port: !udp-port 4450
      send-port: !udp-port 4450
      recv-port: !udp-port 4451

  mongodb:
    enable: true
    hostport: localhost
    collections:
      text-log: llsfrb.log
      clips-log: llsfrb.clipslog
      protobuf: llsfrb.protobuf

  game:
    teams: [b-it-bots, IASLab, SPQR]
    crypto-keys:
      ART: randomkey
      b-it-bots: randomkey
      UvA: randomkey

  shell:
    refbox-host: !ipv4 192.168.1.100
    refbox-port: 4444
